---
name: CI
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
jobs:
  ci-build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        java: [ 8, 11, 17 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - name: Install Docker on macOS
        if: matrix.os == 'macos-latest'
        uses: ./.github/actions/docker-install-macos
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: docker version
        run: docker version
      - name: docker info
        run: docker info
      - name: java version
        run: java -version
      - name: Set up Go
        if: matrix.os == 'windows-latest'
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: debug dns issues on Windows
        if: matrix.os == 'windows-latest'
        run: |
          nslookup registry-1.docker.io
          curl -v https://registry-1.docker.io/
          curl -v https://registry-1.docker.io/v2/
          curl -v --head https://registry-1.docker.io/v2/gesellix/echo-server/manifests/os-windows
          go run .github/check.go
      - name: clean build
        run: ./gradlew clean build --info --stacktrace
      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: '**/build/test-results/test/TEST-*.xml'
...
